package crm_structures

type CreateListMemberships struct {
	Attributes struct {
		Actualclosedate                 int    `json:"actualclosedate"`
		Actualvalue                     int    `json:"actualvalue"`
		ActualvalueBase                 int    `json:"actualvalue_base"`
		Budgetamount                    int    `json:"budgetamount"`
		BudgetamountBase                int    `json:"budgetamount_base"`
		Budgetstatus                    int    `json:"budgetstatus"`
		Campaignid                      string `json:"campaignid"`
		Captureproposalfeedback         bool   `json:"captureproposalfeedback"`
		Closeprobability                int    `json:"closeprobability"`
		Completefinalproposal           bool   `json:"completefinalproposal"`
		Completeinternalreview          bool   `json:"completeinternalreview"`
		Confirminterest                 bool   `json:"confirminterest"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Currentsituation                string `json:"currentsituation"`
		Customerid                      string `json:"customerid"`
		CustomeridAccount               string `json:"customerid_account"`
		CustomeridContact               string `json:"customerid_contact"`
		Customerneed                    string `json:"customerneed"`
		Customerpainpoints              string `json:"customerpainpoints"`
		Decisionmaker                   bool   `json:"decisionmaker"`
		Description                     string `json:"description"`
		Developproposal                 bool   `json:"developproposal"`
		Discountamount                  int    `json:"discountamount"`
		DiscountamountBase              int    `json:"discountamount_base"`
		Discountpercentage              int    `json:"discountpercentage"`
		Estimatedclosedate              int    `json:"estimatedclosedate"`
		Estimatedvalue                  int    `json:"estimatedvalue"`
		EstimatedvalueBase              int    `json:"estimatedvalue_base"`
		Evaluatefit                     bool   `json:"evaluatefit"`
		Exchangerate                    int    `json:"exchangerate"`
		Filedebrief                     bool   `json:"filedebrief"`
		Finaldecisiondate               int    `json:"finaldecisiondate"`
		Freightamount                   int    `json:"freightamount"`
		FreightamountBase               int    `json:"freightamount_base"`
		Identifycompetitors             bool   `json:"identifycompetitors"`
		Identifycustomercontacts        bool   `json:"identifycustomercontacts"`
		Identifypursuitteam             bool   `json:"identifypursuitteam"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Initialcommunication            int    `json:"initialcommunication"`
		IntAddtoforecast                bool   `json:"int_addtoforecast"`
		IntDiscountapproved             bool   `json:"int_discountapproved"`
		IntForecast                     bool   `json:"int_forecast"`
		IntForecastBase                 bool   `json:"int_forecast_base"`
		Isrevenuesystemcalculated       bool   `json:"isrevenuesystemcalculated"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		MsdynOrdertype                  int    `json:"msdyn_ordertype"`
		Name                            string `json:"name"`
		Need                            int    `json:"need"`
		NewAddtoforecast                bool   `json:"new_addtoforecast"`
		NewForecast                     string `json:"new_forecast"`
		NewForecastBase                 string `json:"new_forecast_base"`
		Onholdtime                      int    `json:"onholdtime"`
		Opportunityid                   string `json:"opportunityid"`
		Opportunityratingcode           int    `json:"opportunityratingcode"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Parentaccountid                 string `json:"parentaccountid"`
		Parentcontactid                 string `json:"parentcontactid"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Presentfinalproposal            bool   `json:"presentfinalproposal"`
		Presentproposal                 bool   `json:"presentproposal"`
		Pricelevelid                    string `json:"pricelevelid"`
		Pricingerrorcode                int    `json:"pricingerrorcode"`
		Prioritycode                    int    `json:"prioritycode"`
		Processid                       string `json:"processid"`
		Proposedsolution                string `json:"proposedsolution"`
		Purchaseprocess                 int    `json:"purchaseprocess"`
		Purchasetimeframe               int    `json:"purchasetimeframe"`
		Pursuitdecision                 bool   `json:"pursuitdecision"`
		Qualificationcomments           string `json:"qualificationcomments"`
		Quotecomments                   string `json:"quotecomments"`
		Resolvefeedback                 bool   `json:"resolvefeedback"`
		Salesstage                      int    `json:"salesstage"`
		Salesstagecode                  int    `json:"salesstagecode"`
		SchedulefollowupProspect        int    `json:"schedulefollowup_prospect"`
		SchedulefollowupQualify         int    `json:"schedulefollowup_qualify"`
		Scheduleproposalmeeting         int    `json:"scheduleproposalmeeting"`
		Sendthankyounote                bool   `json:"sendthankyounote"`
		SLAOpportunitySLA               string `json:"sla_opportunity_sla"`
		SlainvokedidOpportunitySLA      string `json:"slainvokedid_opportunity_sla"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Stepid                          string `json:"stepid"`
		Stepname                        string `json:"stepname"`
		Timeline                        int    `json:"timeline"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Totalamount                     int    `json:"totalamount"`
		TotalamountBase                 int    `json:"totalamount_base"`
		Totalamountlessfreight          int    `json:"totalamountlessfreight"`
		TotalamountlessfreightBase      int    `json:"totalamountlessfreight_base"`
		Totaldiscountamount             int    `json:"totaldiscountamount"`
		TotaldiscountamountBase         int    `json:"totaldiscountamount_base"`
		Totallineitemamount             int    `json:"totallineitemamount"`
		TotallineitemamountBase         int    `json:"totallineitemamount_base"`
		Totallineitemdiscountamount     int    `json:"totallineitemdiscountamount"`
		TotallineitemdiscountamountBase int    `json:"totallineitemdiscountamount_base"`
		Totaltax                        int    `json:"totaltax"`
		TotaltaxBase                    int    `json:"totaltax_base"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
type GetListMemberships struct {
	Attributes struct {
		Actualclosedate                 int    `json:"actualclosedate"`
		Actualvalue                     int    `json:"actualvalue"`
		ActualvalueBase                 int    `json:"actualvalue_base"`
		Budgetamount                    int    `json:"budgetamount"`
		BudgetamountBase                int    `json:"budgetamount_base"`
		Budgetstatus                    int    `json:"budgetstatus"`
		Campaignid                      string `json:"campaignid"`
		Captureproposalfeedback         bool   `json:"captureproposalfeedback"`
		Closeprobability                int    `json:"closeprobability"`
		Completefinalproposal           bool   `json:"completefinalproposal"`
		Completeinternalreview          bool   `json:"completeinternalreview"`
		Confirminterest                 bool   `json:"confirminterest"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Currentsituation                string `json:"currentsituation"`
		Customerid                      string `json:"customerid"`
		CustomeridAccount               string `json:"customerid_account"`
		CustomeridContact               string `json:"customerid_contact"`
		Customerneed                    string `json:"customerneed"`
		Customerpainpoints              string `json:"customerpainpoints"`
		Decisionmaker                   bool   `json:"decisionmaker"`
		Description                     string `json:"description"`
		Developproposal                 bool   `json:"developproposal"`
		Discountamount                  int    `json:"discountamount"`
		DiscountamountBase              int    `json:"discountamount_base"`
		Discountpercentage              int    `json:"discountpercentage"`
		Estimatedclosedate              int    `json:"estimatedclosedate"`
		Estimatedvalue                  int    `json:"estimatedvalue"`
		EstimatedvalueBase              int    `json:"estimatedvalue_base"`
		Evaluatefit                     bool   `json:"evaluatefit"`
		Exchangerate                    int    `json:"exchangerate"`
		Filedebrief                     bool   `json:"filedebrief"`
		Finaldecisiondate               int    `json:"finaldecisiondate"`
		Freightamount                   int    `json:"freightamount"`
		FreightamountBase               int    `json:"freightamount_base"`
		Identifycompetitors             bool   `json:"identifycompetitors"`
		Identifycustomercontacts        bool   `json:"identifycustomercontacts"`
		Identifypursuitteam             bool   `json:"identifypursuitteam"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Initialcommunication            int    `json:"initialcommunication"`
		IntAddtoforecast                bool   `json:"int_addtoforecast"`
		IntDiscountapproved             bool   `json:"int_discountapproved"`
		IntForecast                     bool   `json:"int_forecast"`
		IntForecastBase                 bool   `json:"int_forecast_base"`
		Isrevenuesystemcalculated       bool   `json:"isrevenuesystemcalculated"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		MsdynOrdertype                  int    `json:"msdyn_ordertype"`
		Name                            string `json:"name"`
		Need                            int    `json:"need"`
		NewAddtoforecast                bool   `json:"new_addtoforecast"`
		NewForecast                     string `json:"new_forecast"`
		NewForecastBase                 string `json:"new_forecast_base"`
		Onholdtime                      int    `json:"onholdtime"`
		Opportunityid                   string `json:"opportunityid"`
		Opportunityratingcode           int    `json:"opportunityratingcode"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Parentaccountid                 string `json:"parentaccountid"`
		Parentcontactid                 string `json:"parentcontactid"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Presentfinalproposal            bool   `json:"presentfinalproposal"`
		Presentproposal                 bool   `json:"presentproposal"`
		Pricelevelid                    string `json:"pricelevelid"`
		Pricingerrorcode                int    `json:"pricingerrorcode"`
		Prioritycode                    int    `json:"prioritycode"`
		Processid                       string `json:"processid"`
		Proposedsolution                string `json:"proposedsolution"`
		Purchaseprocess                 int    `json:"purchaseprocess"`
		Purchasetimeframe               int    `json:"purchasetimeframe"`
		Pursuitdecision                 bool   `json:"pursuitdecision"`
		Qualificationcomments           string `json:"qualificationcomments"`
		Quotecomments                   string `json:"quotecomments"`
		Resolvefeedback                 bool   `json:"resolvefeedback"`
		Salesstage                      int    `json:"salesstage"`
		Salesstagecode                  int    `json:"salesstagecode"`
		SchedulefollowupProspect        int    `json:"schedulefollowup_prospect"`
		SchedulefollowupQualify         int    `json:"schedulefollowup_qualify"`
		Scheduleproposalmeeting         int    `json:"scheduleproposalmeeting"`
		Sendthankyounote                bool   `json:"sendthankyounote"`
		SLAOpportunitySLA               string `json:"sla_opportunity_sla"`
		SlainvokedidOpportunitySLA      string `json:"slainvokedid_opportunity_sla"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Stepid                          string `json:"stepid"`
		Stepname                        string `json:"stepname"`
		Timeline                        int    `json:"timeline"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Totalamount                     int    `json:"totalamount"`
		TotalamountBase                 int    `json:"totalamount_base"`
		Totalamountlessfreight          int    `json:"totalamountlessfreight"`
		TotalamountlessfreightBase      int    `json:"totalamountlessfreight_base"`
		Totaldiscountamount             int    `json:"totaldiscountamount"`
		TotaldiscountamountBase         int    `json:"totaldiscountamount_base"`
		Totallineitemamount             int    `json:"totallineitemamount"`
		TotallineitemamountBase         int    `json:"totallineitemamount_base"`
		Totallineitemdiscountamount     int    `json:"totallineitemdiscountamount"`
		TotallineitemdiscountamountBase int    `json:"totallineitemdiscountamount_base"`
		Totaltax                        int    `json:"totaltax"`
		TotaltaxBase                    int    `json:"totaltax_base"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool   `json:"fetchMetaInfo"`
	ID            string `json:"id"`
}
type UpdateListMemberships struct {
	Attributes struct {
		Actualclosedate                 int    `json:"actualclosedate"`
		Actualvalue                     int    `json:"actualvalue"`
		ActualvalueBase                 int    `json:"actualvalue_base"`
		Budgetamount                    int    `json:"budgetamount"`
		BudgetamountBase                int    `json:"budgetamount_base"`
		Budgetstatus                    int    `json:"budgetstatus"`
		Campaignid                      string `json:"campaignid"`
		Captureproposalfeedback         bool   `json:"captureproposalfeedback"`
		Closeprobability                int    `json:"closeprobability"`
		Completefinalproposal           bool   `json:"completefinalproposal"`
		Completeinternalreview          bool   `json:"completeinternalreview"`
		Confirminterest                 bool   `json:"confirminterest"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Currentsituation                string `json:"currentsituation"`
		Customerid                      string `json:"customerid"`
		CustomeridAccount               string `json:"customerid_account"`
		CustomeridContact               string `json:"customerid_contact"`
		Customerneed                    string `json:"customerneed"`
		Customerpainpoints              string `json:"customerpainpoints"`
		Decisionmaker                   bool   `json:"decisionmaker"`
		Description                     string `json:"description"`
		Developproposal                 bool   `json:"developproposal"`
		Discountamount                  int    `json:"discountamount"`
		DiscountamountBase              int    `json:"discountamount_base"`
		Discountpercentage              int    `json:"discountpercentage"`
		Estimatedclosedate              int    `json:"estimatedclosedate"`
		Estimatedvalue                  int    `json:"estimatedvalue"`
		EstimatedvalueBase              int    `json:"estimatedvalue_base"`
		Evaluatefit                     bool   `json:"evaluatefit"`
		Exchangerate                    int    `json:"exchangerate"`
		Filedebrief                     bool   `json:"filedebrief"`
		Finaldecisiondate               int    `json:"finaldecisiondate"`
		Freightamount                   int    `json:"freightamount"`
		FreightamountBase               int    `json:"freightamount_base"`
		Identifycompetitors             bool   `json:"identifycompetitors"`
		Identifycustomercontacts        bool   `json:"identifycustomercontacts"`
		Identifypursuitteam             bool   `json:"identifypursuitteam"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Initialcommunication            int    `json:"initialcommunication"`
		IntAddtoforecast                bool   `json:"int_addtoforecast"`
		IntDiscountapproved             bool   `json:"int_discountapproved"`
		IntForecast                     bool   `json:"int_forecast"`
		IntForecastBase                 bool   `json:"int_forecast_base"`
		Isrevenuesystemcalculated       bool   `json:"isrevenuesystemcalculated"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		MsdynOrdertype                  int    `json:"msdyn_ordertype"`
		Name                            string `json:"name"`
		Need                            int    `json:"need"`
		NewAddtoforecast                bool   `json:"new_addtoforecast"`
		NewForecast                     string `json:"new_forecast"`
		NewForecastBase                 string `json:"new_forecast_base"`
		Onholdtime                      int    `json:"onholdtime"`
		Opportunityid                   string `json:"opportunityid"`
		Opportunityratingcode           int    `json:"opportunityratingcode"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Parentaccountid                 string `json:"parentaccountid"`
		Parentcontactid                 string `json:"parentcontactid"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Presentfinalproposal            bool   `json:"presentfinalproposal"`
		Presentproposal                 bool   `json:"presentproposal"`
		Pricelevelid                    string `json:"pricelevelid"`
		Pricingerrorcode                int    `json:"pricingerrorcode"`
		Prioritycode                    int    `json:"prioritycode"`
		Processid                       string `json:"processid"`
		Proposedsolution                string `json:"proposedsolution"`
		Purchaseprocess                 int    `json:"purchaseprocess"`
		Purchasetimeframe               int    `json:"purchasetimeframe"`
		Pursuitdecision                 bool   `json:"pursuitdecision"`
		Qualificationcomments           string `json:"qualificationcomments"`
		Quotecomments                   string `json:"quotecomments"`
		Resolvefeedback                 bool   `json:"resolvefeedback"`
		Salesstage                      int    `json:"salesstage"`
		Salesstagecode                  int    `json:"salesstagecode"`
		SchedulefollowupProspect        int    `json:"schedulefollowup_prospect"`
		SchedulefollowupQualify         int    `json:"schedulefollowup_qualify"`
		Scheduleproposalmeeting         int    `json:"scheduleproposalmeeting"`
		Sendthankyounote                bool   `json:"sendthankyounote"`
		SLAOpportunitySLA               string `json:"sla_opportunity_sla"`
		SlainvokedidOpportunitySLA      string `json:"slainvokedid_opportunity_sla"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Stepid                          string `json:"stepid"`
		Stepname                        string `json:"stepname"`
		Timeline                        int    `json:"timeline"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Totalamount                     int    `json:"totalamount"`
		TotalamountBase                 int    `json:"totalamount_base"`
		Totalamountlessfreight          int    `json:"totalamountlessfreight"`
		TotalamountlessfreightBase      int    `json:"totalamountlessfreight_base"`
		Totaldiscountamount             int    `json:"totaldiscountamount"`
		TotaldiscountamountBase         int    `json:"totaldiscountamount_base"`
		Totallineitemamount             int    `json:"totallineitemamount"`
		TotallineitemamountBase         int    `json:"totallineitemamount_base"`
		Totallineitemdiscountamount     int    `json:"totallineitemdiscountamount"`
		TotallineitemdiscountamountBase int    `json:"totallineitemdiscountamount_base"`
		Totaltax                        int    `json:"totaltax"`
		TotaltaxBase                    int    `json:"totaltax_base"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
