package crm_structures

type CreateLayoutTemplates struct {
	Attributes struct {
		Createdby                   string `json:"createdby"`
		Createdon                   int    `json:"createdon"`
		Createdonbehalfby           string `json:"createdonbehalfby"`
		Currentcost                 int    `json:"currentcost"`
		CurrentcostBase             int    `json:"currentcost_base"`
		Defaultuomid                string `json:"defaultuomid"`
		Defaultuomscheduleid        string `json:"defaultuomscheduleid"`
		Description                 string `json:"description"`
		Dmtimportstate              int    `json:"dmtimportstate"`
		Entityimage                 string `json:"entityimage"`
		EntityimageTimestamp        int    `json:"entityimage_timestamp"`
		EntityimageURL              string `json:"entityimage_url"`
		Entityimageid               string `json:"entityimageid"`
		Exchangerate                int    `json:"exchangerate"`
		Hierarchypath               string `json:"hierarchypath"`
		Importsequencenumber        int    `json:"importsequencenumber"`
		Iskit                       bool   `json:"iskit"`
		Isstockitem                 bool   `json:"isstockitem"`
		Modifiedby                  string `json:"modifiedby"`
		Modifiedon                  int    `json:"modifiedon"`
		Modifiedonbehalfby          string `json:"modifiedonbehalfby"`
		MsdynConverttocustomerasset bool   `json:"msdyn_converttocustomerasset"`
		MsdynPurchasename           string `json:"msdyn_purchasename"`
		MsdynTaxable                bool   `json:"msdyn_taxable"`
		Name                        string `json:"name"`
		Organizationid              string `json:"organizationid"`
		Overriddencreatedon         int    `json:"overriddencreatedon"`
		Parentproductid             string `json:"parentproductid"`
		Price                       int    `json:"price"`
		PriceBase                   int    `json:"price_base"`
		Pricelevelid                string `json:"pricelevelid"`
		Processid                   string `json:"processid"`
		Productid                   string `json:"productid"`
		Productnumber               string `json:"productnumber"`
		LayoutTemplatestructure     int    `json:"LayoutTemplatestructure"`
		Producttypecode             int    `json:"producttypecode"`
		Producturl                  string `json:"producturl"`
		Quantitydecimal             int    `json:"quantitydecimal"`
		Quantityonhand              int    `json:"quantityonhand"`
		Size                        string `json:"size"`
		Stageid                     string `json:"stageid"`
		StageidProcessstage         string `json:"stageid_processstage"`
		Standardcost                int    `json:"standardcost"`
		StandardcostBase            int    `json:"standardcost_base"`
		Statecode                   int    `json:"statecode"`
		Statuscode                  int    `json:"statuscode"`
		Stockvolume                 int    `json:"stockvolume"`
		Stockweight                 int    `json:"stockweight"`
		Subjectid                   string `json:"subjectid"`
		Suppliername                string `json:"suppliername"`
		Timezoneruleversionnumber   int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid       string `json:"transactioncurrencyid"`
		Traversedpath               string `json:"traversedpath"`
		Utcconversiontimezonecode   int    `json:"utcconversiontimezonecode"`
		Validfromdate               int    `json:"validfromdate"`
		Validtodate                 int    `json:"validtodate"`
		Vendorid                    string `json:"vendorid"`
		Vendorname                  string `json:"vendorname"`
		Vendorpartnumber            string `json:"vendorpartnumber"`
		Versionnumber               int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
type GetLayoutTemplates struct {
	Attributes struct {
		Createdby                    string `json:"createdby"`
		Createdon                    int    `json:"createdon"`
		Createdonbehalfby            string `json:"createdonbehalfby"`
		Currentcost                  int    `json:"currentcost"`
		CurrentcostBase              int    `json:"currentcost_base"`
		Defaultuomid                 string `json:"defaultuomid"`
		Defaultuomscheduleid         string `json:"defaultuomscheduleid"`
		Description                  string `json:"description"`
		Dmtimportstate               int    `json:"dmtimportstate"`
		Entityimage                  string `json:"entityimage"`
		EntityimageTimestamp         int    `json:"entityimage_timestamp"`
		EntityimageURL               string `json:"entityimage_url"`
		Entityimageid                string `json:"entityimageid"`
		Exchangerate                 int    `json:"exchangerate"`
		Hierarchypath                string `json:"hierarchypath"`
		Importsequencenumber         int    `json:"importsequencenumber"`
		Iskit                        bool   `json:"iskit"`
		Isstockitem                  bool   `json:"isstockitem"`
		Modifiedby                   string `json:"modifiedby"`
		Modifiedon                   int    `json:"modifiedon"`
		Modifiedonbehalfby           string `json:"modifiedonbehalfby"`
		MsdynConverttocustomerasset  bool   `json:"msdyn_converttocustomerasset"`
		MsdynFieldserviceproducttype int    `json:"msdyn_fieldserviceproducttype"`
		MsdynPurchasename            string `json:"msdyn_purchasename"`
		MsdynTaxable                 bool   `json:"msdyn_taxable"`
		Name                         string `json:"name"`
		NewBrofield                  string `json:"new_brofield"`
		NewCustomintfield            int    `json:"new_customintfield"`
		Organizationid               string `json:"organizationid"`
		Overriddencreatedon          int    `json:"overriddencreatedon"`
		Parentproductid              string `json:"parentproductid"`
		Price                        int    `json:"price"`
		PriceBase                    int    `json:"price_base"`
		Pricelevelid                 string `json:"pricelevelid"`
		Processid                    string `json:"processid"`
		Productid                    string `json:"productid"`
		Productnumber                string `json:"productnumber"`
		LayoutTemplatestructure      int    `json:"LayoutTemplatestructure"`
		Producttypecode              int    `json:"producttypecode"`
		Producturl                   string `json:"producturl"`
		Quantitydecimal              int    `json:"quantitydecimal"`
		Quantityonhand               int    `json:"quantityonhand"`
		Size                         string `json:"size"`
		Stageid                      string `json:"stageid"`
		StageidProcessstage          string `json:"stageid_processstage"`
		Standardcost                 int    `json:"standardcost"`
		StandardcostBase             int    `json:"standardcost_base"`
		Statecode                    int    `json:"statecode"`
		Statuscode                   int    `json:"statuscode"`
		Stockvolume                  int    `json:"stockvolume"`
		Stockweight                  int    `json:"stockweight"`
		Subjectid                    string `json:"subjectid"`
		Suppliername                 string `json:"suppliername"`
		Timezoneruleversionnumber    int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid        string `json:"transactioncurrencyid"`
		Traversedpath                string `json:"traversedpath"`
		Utcconversiontimezonecode    int    `json:"utcconversiontimezonecode"`
		Validfromdate                int    `json:"validfromdate"`
		Validtodate                  int    `json:"validtodate"`
		Vendorid                     string `json:"vendorid"`
		Vendorname                   string `json:"vendorname"`
		Vendorpartnumber             string `json:"vendorpartnumber"`
		Versionnumber                int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool   `json:"fetchMetaInfo"`
	ID            string `json:"id"`
}
type UpdateLayoutTemplates struct {
	Attributes struct {
		Createdby                   string `json:"createdby"`
		Createdon                   int    `json:"createdon"`
		Createdonbehalfby           string `json:"createdonbehalfby"`
		Currentcost                 int    `json:"currentcost"`
		CurrentcostBase             int    `json:"currentcost_base"`
		Defaultuomid                string `json:"defaultuomid"`
		Defaultuomscheduleid        string `json:"defaultuomscheduleid"`
		Description                 string `json:"description"`
		Dmtimportstate              int    `json:"dmtimportstate"`
		Entityimage                 string `json:"entityimage"`
		EntityimageTimestamp        int    `json:"entityimage_timestamp"`
		EntityimageURL              string `json:"entityimage_url"`
		Entityimageid               string `json:"entityimageid"`
		Exchangerate                int    `json:"exchangerate"`
		Hierarchypath               string `json:"hierarchypath"`
		Importsequencenumber        int    `json:"importsequencenumber"`
		Iskit                       bool   `json:"iskit"`
		Isstockitem                 bool   `json:"isstockitem"`
		Modifiedby                  string `json:"modifiedby"`
		Modifiedon                  int    `json:"modifiedon"`
		Modifiedonbehalfby          string `json:"modifiedonbehalfby"`
		MsdynConverttocustomerasset bool   `json:"msdyn_converttocustomerasset"`
		MsdynPurchasename           string `json:"msdyn_purchasename"`
		MsdynTaxable                bool   `json:"msdyn_taxable"`
		Name                        string `json:"name"`
		Organizationid              string `json:"organizationid"`
		Overriddencreatedon         int    `json:"overriddencreatedon"`
		Parentproductid             string `json:"parentproductid"`
		Price                       int    `json:"price"`
		PriceBase                   int    `json:"price_base"`
		Pricelevelid                string `json:"pricelevelid"`
		Processid                   string `json:"processid"`
		Productid                   string `json:"productid"`
		Productnumber               string `json:"productnumber"`
		LayoutTemplatestructure     int    `json:"LayoutTemplatestructure"`
		Producttypecode             int    `json:"producttypecode"`
		Producturl                  string `json:"producturl"`
		Quantitydecimal             int    `json:"quantitydecimal"`
		Quantityonhand              int    `json:"quantityonhand"`
		Size                        string `json:"size"`
		Stageid                     string `json:"stageid"`
		StageidProcessstage         string `json:"stageid_processstage"`
		Standardcost                int    `json:"standardcost"`
		StandardcostBase            int    `json:"standardcost_base"`
		Statecode                   int    `json:"statecode"`
		Statuscode                  int    `json:"statuscode"`
		Stockvolume                 int    `json:"stockvolume"`
		Stockweight                 int    `json:"stockweight"`
		Subjectid                   string `json:"subjectid"`
		Suppliername                string `json:"suppliername"`
		Timezoneruleversionnumber   int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid       string `json:"transactioncurrencyid"`
		Traversedpath               string `json:"traversedpath"`
		Utcconversiontimezonecode   int    `json:"utcconversiontimezonecode"`
		Validfromdate               int    `json:"validfromdate"`
		Validtodate                 int    `json:"validtodate"`
		Vendorid                    string `json:"vendorid"`
		Vendorname                  string `json:"vendorname"`
		Vendorpartnumber            string `json:"vendorpartnumber"`
		Versionnumber               int    `json:"versionnumber"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
