package crm_structures

type GetUsers struct {
	Attributes struct {
		Accessmode                        int    `json:"accessmode"`
		Address1Addressid                 string `json:"address1_addressid"`
		Address1Addresstypecode           int    `json:"address1_addresstypecode"`
		Address1City                      string `json:"address1_city"`
		Address1Composite                 string `json:"address1_composite"`
		Address1Country                   string `json:"address1_country"`
		Address1County                    string `json:"address1_county"`
		Address1Fax                       string `json:"address1_fax"`
		Address1Latitude                  int    `json:"address1_latitude"`
		Address1Line1                     string `json:"address1_line1"`
		Address1Line2                     string `json:"address1_line2"`
		Address1Line3                     string `json:"address1_line3"`
		Address1Longitude                 int    `json:"address1_longitude"`
		Address1Name                      string `json:"address1_name"`
		Address1Postalcode                string `json:"address1_postalcode"`
		Address1Postofficebox             string `json:"address1_postofficebox"`
		Address1Shippingmethodcode        int    `json:"address1_shippingmethodcode"`
		Address1Stateorprovince           string `json:"address1_stateorprovince"`
		Address1Telephone1                string `json:"address1_telephone1"`
		Address1Telephone2                string `json:"address1_telephone2"`
		Address1Telephone3                string `json:"address1_telephone3"`
		Address1Upszone                   string `json:"address1_upszone"`
		Address1Utcoffset                 int    `json:"address1_utcoffset"`
		Address2Addressid                 string `json:"address2_addressid"`
		Address2Addresstypecode           int    `json:"address2_addresstypecode"`
		Address2City                      string `json:"address2_city"`
		Address2Composite                 string `json:"address2_composite"`
		Address2Country                   string `json:"address2_country"`
		Address2County                    string `json:"address2_county"`
		Address2Fax                       string `json:"address2_fax"`
		Address2Latitude                  int    `json:"address2_latitude"`
		Address2Line1                     string `json:"address2_line1"`
		Address2Line2                     string `json:"address2_line2"`
		Address2Line3                     string `json:"address2_line3"`
		Address2Longitude                 int    `json:"address2_longitude"`
		Address2Name                      string `json:"address2_name"`
		Address2Postalcode                string `json:"address2_postalcode"`
		Address2Postofficebox             string `json:"address2_postofficebox"`
		Address2Shippingmethodcode        int    `json:"address2_shippingmethodcode"`
		Address2Stateorprovince           string `json:"address2_stateorprovince"`
		Address2Telephone1                string `json:"address2_telephone1"`
		Address2Telephone2                string `json:"address2_telephone2"`
		Address2Telephone3                string `json:"address2_telephone3"`
		Address2Upszone                   string `json:"address2_upszone"`
		Address2Utcoffset                 int    `json:"address2_utcoffset"`
		Applicationid                     string `json:"applicationid"`
		Applicationiduri                  string `json:"applicationiduri"`
		Azureactivedirectoryobjectid      string `json:"azureactivedirectoryobjectid"`
		Businessunitid                    string `json:"businessunitid"`
		Calendarid                        string `json:"calendarid"`
		Caltype                           int    `json:"caltype"`
		Createdby                         string `json:"createdby"`
		Createdon                         int    `json:"createdon"`
		Createdonbehalfby                 string `json:"createdonbehalfby"`
		Defaultfilterspopulated           bool   `json:"defaultfilterspopulated"`
		Defaultmailbox                    string `json:"defaultmailbox"`
		Defaultodbfoldername              string `json:"defaultodbfoldername"`
		Disabledreason                    string `json:"disabledreason"`
		Displayinserviceviews             bool   `json:"displayinserviceviews"`
		Domainname                        string `json:"domainname"`
		Emailrouteraccessapproval         int    `json:"emailrouteraccessapproval"`
		Employeeid                        string `json:"employeeid"`
		Entityimage                       string `json:"entityimage"`
		EntityimageTimestamp              int    `json:"entityimage_timestamp"`
		EntityimageURL                    string `json:"entityimage_url"`
		Entityimageid                     string `json:"entityimageid"`
		Exchangerate                      int    `json:"exchangerate"`
		Firstname                         string `json:"firstname"`
		Fullname                          string `json:"fullname"`
		Governmentid                      string `json:"governmentid"`
		Homephone                         string `json:"homephone"`
		Importsequencenumber              int    `json:"importsequencenumber"`
		Incomingemaildeliverymethod       int    `json:"incomingemaildeliverymethod"`
		Internalemailaddress              string `json:"internalemailaddress"`
		Invitestatuscode                  int    `json:"invitestatuscode"`
		Isdisabled                        bool   `json:"isdisabled"`
		Isemailaddressapprovedbyo365Admin bool   `json:"isemailaddressapprovedbyo365admin"`
		Isintegrationuser                 bool   `json:"isintegrationuser"`
		Islicensed                        bool   `json:"islicensed"`
		Issyncwithdirectory               bool   `json:"issyncwithdirectory"`
		Jobtitle                          string `json:"jobtitle"`
		Lastname                          string `json:"lastname"`
		Middlename                        string `json:"middlename"`
		Mobilealertemail                  string `json:"mobilealertemail"`
		Mobileofflineprofileid            string `json:"mobileofflineprofileid"`
		Mobilephone                       string `json:"mobilephone"`
		Modifiedby                        string `json:"modifiedby"`
		Modifiedon                        int    `json:"modifiedon"`
		Modifiedonbehalfby                string `json:"modifiedonbehalfby"`
		Nickname                          string `json:"nickname"`
		Organizationid                    string `json:"organizationid"`
		OrganizationidOrganization        string `json:"organizationid_organization"`
		Outgoingemaildeliverymethod       int    `json:"outgoingemaildeliverymethod"`
		Overriddencreatedon               int    `json:"overriddencreatedon"`
		Ownerid                           string `json:"ownerid"`
		Parentsystemuserid                string `json:"parentsystemuserid"`
		Passporthi                        int    `json:"passporthi"`
		Passportlo                        int    `json:"passportlo"`
		Personalemailaddress              string `json:"personalemailaddress"`
		Photourl                          string `json:"photourl"`
		Positionid                        string `json:"positionid"`
		Preferredaddresscode              int    `json:"preferredaddresscode"`
		Preferredemailcode                int    `json:"preferredemailcode"`
		Preferredphonecode                int    `json:"preferredphonecode"`
		Processid                         string `json:"processid"`
		Queueid                           string `json:"queueid"`
		Salutation                        string `json:"salutation"`
		Setupuser                         bool   `json:"setupuser"`
		Sharepointemailaddress            string `json:"sharepointemailaddress"`
		Siteid                            string `json:"siteid"`
		Skills                            string `json:"skills"`
		Stageid                           string `json:"stageid"`
		StageidProcessstage               string `json:"stageid_processstage"`
		Systemuserid                      string `json:"systemuserid"`
		Territoryid                       string `json:"territoryid"`
		Timezoneruleversionnumber         int    `json:"timezoneruleversionnumber"`
		Title                             string `json:"title"`
		Transactioncurrencyid             string `json:"transactioncurrencyid"`
		Traversedpath                     string `json:"traversedpath"`
		Userlicensetype                   int    `json:"userlicensetype"`
		Utcconversiontimezonecode         int    `json:"utcconversiontimezonecode"`
		Versionnumber                     int    `json:"versionnumber"`
		Windowsliveid                     string `json:"windowsliveid"`
		Yammeremailaddress                string `json:"yammeremailaddress"`
		Yammeruserid                      string `json:"yammeruserid"`
		Yomifirstname                     string `json:"yomifirstname"`
		Yomifullname                      string `json:"yomifullname"`
		Yomilastname                      string `json:"yomilastname"`
		Yomimiddlename                    string `json:"yomimiddlename"`
	} `json:"attributes"`
	ID string `json:"id"`
}
