package crm_structures

type GetCampaigns struct {
	Attributes struct {
		Accountcategorycode             int    `json:"accountcategorycode"`
		Accountclassificationcode       int    `json:"accountclassificationcode"`
		Accountid                       string `json:"accountid"`
		Accountnumber                   string `json:"accountnumber"`
		Accountratingcode               int    `json:"accountratingcode"`
		Address1Addressid               string `json:"address1_addressid"`
		Address1Addresstypecode         int    `json:"address1_addresstypecode"`
		Address1City                    string `json:"address1_city"`
		Address1Composite               string `json:"address1_composite"`
		Address1Country                 string `json:"address1_country"`
		Address1County                  string `json:"address1_county"`
		Address1Fax                     string `json:"address1_fax"`
		Address1Freighttermscode        int    `json:"address1_freighttermscode"`
		Address1Latitude                int    `json:"address1_latitude"`
		Address1Line1                   string `json:"address1_line1"`
		Address1Line2                   string `json:"address1_line2"`
		Address1Line3                   string `json:"address1_line3"`
		Address1Longitude               int    `json:"address1_longitude"`
		Address1Name                    string `json:"address1_name"`
		Address1Postalcode              string `json:"address1_postalcode"`
		Address1Postofficebox           string `json:"address1_postofficebox"`
		Address1Primarycontactname      string `json:"address1_primarycontactname"`
		Address1Shippingmethodcode      int    `json:"address1_shippingmethodcode"`
		Address1Stateorprovince         string `json:"address1_stateorprovince"`
		Address1Telephone1              string `json:"address1_telephone1"`
		Address1Telephone2              string `json:"address1_telephone2"`
		Address1Telephone3              string `json:"address1_telephone3"`
		Address1Upszone                 string `json:"address1_upszone"`
		Address1Utcoffset               int    `json:"address1_utcoffset"`
		Address2Addressid               string `json:"address2_addressid"`
		Address2Addresstypecode         int    `json:"address2_addresstypecode"`
		Address2City                    string `json:"address2_city"`
		Address2Composite               string `json:"address2_composite"`
		Address2Country                 string `json:"address2_country"`
		Address2County                  string `json:"address2_county"`
		Address2Fax                     string `json:"address2_fax"`
		Address2Freighttermscode        int    `json:"address2_freighttermscode"`
		Address2Latitude                int    `json:"address2_latitude"`
		Address2Line1                   string `json:"address2_line1"`
		Address2Line2                   string `json:"address2_line2"`
		Address2Line3                   string `json:"address2_line3"`
		Address2Longitude               int    `json:"address2_longitude"`
		Address2Name                    string `json:"address2_name"`
		Address2Postalcode              string `json:"address2_postalcode"`
		Address2Postofficebox           string `json:"address2_postofficebox"`
		Address2Primarycontactname      string `json:"address2_primarycontactname"`
		Address2Shippingmethodcode      int    `json:"address2_shippingmethodcode"`
		Address2Stateorprovince         string `json:"address2_stateorprovince"`
		Address2Telephone1              string `json:"address2_telephone1"`
		Address2Telephone2              string `json:"address2_telephone2"`
		Address2Telephone3              string `json:"address2_telephone3"`
		Address2Upszone                 string `json:"address2_upszone"`
		Address2Utcoffset               int    `json:"address2_utcoffset"`
		Aging30                         int    `json:"aging30"`
		Aging30Base                     int    `json:"aging30_base"`
		Aging60                         int    `json:"aging60"`
		Aging60Base                     int    `json:"aging60_base"`
		Aging90                         int    `json:"aging90"`
		Aging90Base                     int    `json:"aging90_base"`
		Businesstypecode                int    `json:"businesstypecode"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Creditlimit                     int    `json:"creditlimit"`
		CreditlimitBase                 int    `json:"creditlimit_base"`
		Creditonhold                    bool   `json:"creditonhold"`
		Customersizecode                int    `json:"customersizecode"`
		Customertypecode                int    `json:"customertypecode"`
		Defaultpricelevelid             string `json:"defaultpricelevelid"`
		Description                     string `json:"description"`
		Donotbulkemail                  bool   `json:"donotbulkemail"`
		Donotbulkpostalmail             bool   `json:"donotbulkpostalmail"`
		Donotemail                      bool   `json:"donotemail"`
		Donotfax                        bool   `json:"donotfax"`
		Donotphone                      bool   `json:"donotphone"`
		Donotpostalmail                 bool   `json:"donotpostalmail"`
		Donotsendmm                     bool   `json:"donotsendmm"`
		Emailaddress1                   string `json:"emailaddress1"`
		Emailaddress2                   string `json:"emailaddress2"`
		Emailaddress3                   string `json:"emailaddress3"`
		Entityimage                     string `json:"entityimage"`
		EntityimageTimestamp            int    `json:"entityimage_timestamp"`
		EntityimageURL                  string `json:"entityimage_url"`
		Entityimageid                   string `json:"entityimageid"`
		Exchangerate                    int    `json:"exchangerate"`
		Fax                             string `json:"fax"`
		Followemail                     bool   `json:"followemail"`
		Ftpsiteurl                      string `json:"ftpsiteurl"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Industrycode                    int    `json:"industrycode"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Lastusedincampaign              int    `json:"lastusedincampaign"`
		Marketcap                       int    `json:"marketcap"`
		MarketcapBase                   int    `json:"marketcap_base"`
		Marketingonly                   bool   `json:"marketingonly"`
		Masterid                        string `json:"masterid"`
		Merged                          bool   `json:"merged"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		MsdynTaxexempt                  bool   `json:"msdyn_taxexempt"`
		Name                            string `json:"name"`
		Numberofemployees               int    `json:"numberofemployees"`
		Onholdtime                      int    `json:"onholdtime"`
		Opendeals                       int    `json:"opendeals"`
		OpendealsDate                   int    `json:"opendeals_date"`
		OpendealsState                  int    `json:"opendeals_state"`
		Openrevenue                     int    `json:"openrevenue"`
		OpenrevenueBase                 int    `json:"openrevenue_base"`
		OpenrevenueDate                 int    `json:"openrevenue_date"`
		OpenrevenueState                int    `json:"openrevenue_state"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Ownershipcode                   int    `json:"ownershipcode"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Parentaccountid                 string `json:"parentaccountid"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Paymenttermscode                int    `json:"paymenttermscode"`
		Preferredappointmentdaycode     int    `json:"preferredappointmentdaycode"`
		Preferredappointmenttimecode    int    `json:"preferredappointmenttimecode"`
		Preferredcontactmethodcode      int    `json:"preferredcontactmethodcode"`
		Preferredequipmentid            string `json:"preferredequipmentid"`
		Preferredserviceid              string `json:"preferredserviceid"`
		Preferredsystemuserid           string `json:"preferredsystemuserid"`
		Primarycontactid                string `json:"primarycontactid"`
		Primarysatoriid                 string `json:"primarysatoriid"`
		Primarytwitterid                string `json:"primarytwitterid"`
		Processid                       string `json:"processid"`
		Revenue                         int    `json:"revenue"`
		RevenueBase                     int    `json:"revenue_base"`
		Sharesoutstanding               int    `json:"sharesoutstanding"`
		Shippingmethodcode              int    `json:"shippingmethodcode"`
		Sic                             string `json:"sic"`
		SLACampaignsLA                  string `json:"sla_account_sla"`
		SlainvokedidCampaignsLA         string `json:"slainvokedid_account_sla"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Stockexchange                   string `json:"stockexchange"`
		Telephone1                      string `json:"telephone1"`
		Telephone2                      string `json:"telephone2"`
		Telephone3                      string `json:"telephone3"`
		Territorycode                   int    `json:"territorycode"`
		Territoryid                     string `json:"territoryid"`
		Tickersymbol                    string `json:"tickersymbol"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
		Websiteurl                      string `json:"websiteurl"`
		Yominame                        string `json:"yominame"`
	} `json:"attributes"`
	FetchMetaInfo bool   `json:"fetchMetaInfo"`
	ID            string `json:"id"`
}
type CreateCampaigns struct {
	Attributes struct {
		Accountcategorycode             int    `json:"accountcategorycode"`
		Accountclassificationcode       int    `json:"accountclassificationcode"`
		Accountid                       string `json:"accountid"`
		Accountnumber                   string `json:"accountnumber"`
		Accountratingcode               int    `json:"accountratingcode"`
		Address1Addressid               string `json:"address1_addressid"`
		Address1Addresstypecode         int    `json:"address1_addresstypecode"`
		Address1City                    string `json:"address1_city"`
		Address1Composite               string `json:"address1_composite"`
		Address1Country                 string `json:"address1_country"`
		Address1County                  string `json:"address1_county"`
		Address1Fax                     string `json:"address1_fax"`
		Address1Freighttermscode        int    `json:"address1_freighttermscode"`
		Address1Latitude                int    `json:"address1_latitude"`
		Address1Line1                   string `json:"address1_line1"`
		Address1Line2                   string `json:"address1_line2"`
		Address1Line3                   string `json:"address1_line3"`
		Address1Longitude               int    `json:"address1_longitude"`
		Address1Name                    string `json:"address1_name"`
		Address1Postalcode              string `json:"address1_postalcode"`
		Address1Postofficebox           string `json:"address1_postofficebox"`
		Address1Primarycontactname      string `json:"address1_primarycontactname"`
		Address1Shippingmethodcode      int    `json:"address1_shippingmethodcode"`
		Address1Stateorprovince         string `json:"address1_stateorprovince"`
		Address1Telephone1              string `json:"address1_telephone1"`
		Address1Telephone2              string `json:"address1_telephone2"`
		Address1Telephone3              string `json:"address1_telephone3"`
		Address1Upszone                 string `json:"address1_upszone"`
		Address1Utcoffset               int    `json:"address1_utcoffset"`
		Address2Addressid               string `json:"address2_addressid"`
		Address2Addresstypecode         int    `json:"address2_addresstypecode"`
		Address2City                    string `json:"address2_city"`
		Address2Composite               string `json:"address2_composite"`
		Address2Country                 string `json:"address2_country"`
		Address2County                  string `json:"address2_county"`
		Address2Fax                     string `json:"address2_fax"`
		Address2Freighttermscode        int    `json:"address2_freighttermscode"`
		Address2Latitude                int    `json:"address2_latitude"`
		Address2Line1                   string `json:"address2_line1"`
		Address2Line2                   string `json:"address2_line2"`
		Address2Line3                   string `json:"address2_line3"`
		Address2Longitude               int    `json:"address2_longitude"`
		Address2Name                    string `json:"address2_name"`
		Address2Postalcode              string `json:"address2_postalcode"`
		Address2Postofficebox           string `json:"address2_postofficebox"`
		Address2Primarycontactname      string `json:"address2_primarycontactname"`
		Address2Shippingmethodcode      int    `json:"address2_shippingmethodcode"`
		Address2Stateorprovince         string `json:"address2_stateorprovince"`
		Address2Telephone1              string `json:"address2_telephone1"`
		Address2Telephone2              string `json:"address2_telephone2"`
		Address2Telephone3              string `json:"address2_telephone3"`
		Address2Upszone                 string `json:"address2_upszone"`
		Address2Utcoffset               int    `json:"address2_utcoffset"`
		Aging30                         int    `json:"aging30"`
		Aging30Base                     int    `json:"aging30_base"`
		Aging60                         int    `json:"aging60"`
		Aging60Base                     int    `json:"aging60_base"`
		Aging90                         int    `json:"aging90"`
		Aging90Base                     int    `json:"aging90_base"`
		Businesstypecode                int    `json:"businesstypecode"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Creditlimit                     int    `json:"creditlimit"`
		CreditlimitBase                 int    `json:"creditlimit_base"`
		Creditonhold                    bool   `json:"creditonhold"`
		Customersizecode                int    `json:"customersizecode"`
		Customertypecode                int    `json:"customertypecode"`
		Defaultpricelevelid             string `json:"defaultpricelevelid"`
		Description                     string `json:"description"`
		Donotbulkemail                  bool   `json:"donotbulkemail"`
		Donotbulkpostalmail             bool   `json:"donotbulkpostalmail"`
		Donotemail                      bool   `json:"donotemail"`
		Donotfax                        bool   `json:"donotfax"`
		Donotphone                      bool   `json:"donotphone"`
		Donotpostalmail                 bool   `json:"donotpostalmail"`
		Donotsendmm                     bool   `json:"donotsendmm"`
		Emailaddress1                   string `json:"emailaddress1"`
		Emailaddress2                   string `json:"emailaddress2"`
		Emailaddress3                   string `json:"emailaddress3"`
		Entityimage                     string `json:"entityimage"`
		EntityimageTimestamp            int    `json:"entityimage_timestamp"`
		EntityimageURL                  string `json:"entityimage_url"`
		Entityimageid                   string `json:"entityimageid"`
		Exchangerate                    int    `json:"exchangerate"`
		Fax                             string `json:"fax"`
		Followemail                     bool   `json:"followemail"`
		Ftpsiteurl                      string `json:"ftpsiteurl"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Industrycode                    int    `json:"industrycode"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Lastusedincampaign              int    `json:"lastusedincampaign"`
		Marketcap                       int    `json:"marketcap"`
		MarketcapBase                   int    `json:"marketcap_base"`
		Marketingonly                   bool   `json:"marketingonly"`
		Masterid                        string `json:"masterid"`
		Merged                          bool   `json:"merged"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		MsdynTaxexempt                  bool   `json:"msdyn_taxexempt"`
		Name                            string `json:"name"`
		Numberofemployees               int    `json:"numberofemployees"`
		Onholdtime                      int    `json:"onholdtime"`
		Opendeals                       int    `json:"opendeals"`
		OpendealsDate                   int    `json:"opendeals_date"`
		OpendealsState                  int    `json:"opendeals_state"`
		Openrevenue                     int    `json:"openrevenue"`
		OpenrevenueBase                 int    `json:"openrevenue_base"`
		OpenrevenueDate                 int    `json:"openrevenue_date"`
		OpenrevenueState                int    `json:"openrevenue_state"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Ownershipcode                   int    `json:"ownershipcode"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Parentaccountid                 string `json:"parentaccountid"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Paymenttermscode                int    `json:"paymenttermscode"`
		Preferredappointmentdaycode     int    `json:"preferredappointmentdaycode"`
		Preferredappointmenttimecode    int    `json:"preferredappointmenttimecode"`
		Preferredcontactmethodcode      int    `json:"preferredcontactmethodcode"`
		Preferredequipmentid            string `json:"preferredequipmentid"`
		Preferredserviceid              string `json:"preferredserviceid"`
		Preferredsystemuserid           string `json:"preferredsystemuserid"`
		Primarycontactid                string `json:"primarycontactid"`
		Primarysatoriid                 string `json:"primarysatoriid"`
		Primarytwitterid                string `json:"primarytwitterid"`
		Processid                       string `json:"processid"`
		Revenue                         int    `json:"revenue"`
		RevenueBase                     int    `json:"revenue_base"`
		Sharesoutstanding               int    `json:"sharesoutstanding"`
		Shippingmethodcode              int    `json:"shippingmethodcode"`
		Sic                             string `json:"sic"`
		SLACampaignsLA                  string `json:"sla_account_sla"`
		SlainvokedidCampaignsLA         string `json:"slainvokedid_account_sla"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Stockexchange                   string `json:"stockexchange"`
		Telephone1                      string `json:"telephone1"`
		Telephone2                      string `json:"telephone2"`
		Telephone3                      string `json:"telephone3"`
		Territorycode                   int    `json:"territorycode"`
		Territoryid                     string `json:"territoryid"`
		Tickersymbol                    string `json:"tickersymbol"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
		Websiteurl                      string `json:"websiteurl"`
		Yominame                        string `json:"yominame"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
type UpdateCampaigns struct {
	Attributes struct {
		Accountcategorycode             int    `json:"accountcategorycode"`
		Accountclassificationcode       int    `json:"accountclassificationcode"`
		Accountid                       string `json:"accountid"`
		Accountnumber                   string `json:"accountnumber"`
		Accountratingcode               int    `json:"accountratingcode"`
		Address1Addressid               string `json:"address1_addressid"`
		Address1Addresstypecode         int    `json:"address1_addresstypecode"`
		Address1City                    string `json:"address1_city"`
		Address1Composite               string `json:"address1_composite"`
		Address1Country                 string `json:"address1_country"`
		Address1County                  string `json:"address1_county"`
		Address1Fax                     string `json:"address1_fax"`
		Address1Freighttermscode        int    `json:"address1_freighttermscode"`
		Address1Latitude                int    `json:"address1_latitude"`
		Address1Line1                   string `json:"address1_line1"`
		Address1Line2                   string `json:"address1_line2"`
		Address1Line3                   string `json:"address1_line3"`
		Address1Longitude               int    `json:"address1_longitude"`
		Address1Name                    string `json:"address1_name"`
		Address1Postalcode              string `json:"address1_postalcode"`
		Address1Postofficebox           string `json:"address1_postofficebox"`
		Address1Primarycontactname      string `json:"address1_primarycontactname"`
		Address1Shippingmethodcode      int    `json:"address1_shippingmethodcode"`
		Address1Stateorprovince         string `json:"address1_stateorprovince"`
		Address1Telephone1              string `json:"address1_telephone1"`
		Address1Telephone2              string `json:"address1_telephone2"`
		Address1Telephone3              string `json:"address1_telephone3"`
		Address1Upszone                 string `json:"address1_upszone"`
		Address1Utcoffset               int    `json:"address1_utcoffset"`
		Address2Addressid               string `json:"address2_addressid"`
		Address2Addresstypecode         int    `json:"address2_addresstypecode"`
		Address2City                    string `json:"address2_city"`
		Address2Composite               string `json:"address2_composite"`
		Address2Country                 string `json:"address2_country"`
		Address2County                  string `json:"address2_county"`
		Address2Fax                     string `json:"address2_fax"`
		Address2Freighttermscode        int    `json:"address2_freighttermscode"`
		Address2Latitude                int    `json:"address2_latitude"`
		Address2Line1                   string `json:"address2_line1"`
		Address2Line2                   string `json:"address2_line2"`
		Address2Line3                   string `json:"address2_line3"`
		Address2Longitude               int    `json:"address2_longitude"`
		Address2Name                    string `json:"address2_name"`
		Address2Postalcode              string `json:"address2_postalcode"`
		Address2Postofficebox           string `json:"address2_postofficebox"`
		Address2Primarycontactname      string `json:"address2_primarycontactname"`
		Address2Shippingmethodcode      int    `json:"address2_shippingmethodcode"`
		Address2Stateorprovince         string `json:"address2_stateorprovince"`
		Address2Telephone1              string `json:"address2_telephone1"`
		Address2Telephone2              string `json:"address2_telephone2"`
		Address2Telephone3              string `json:"address2_telephone3"`
		Address2Upszone                 string `json:"address2_upszone"`
		Address2Utcoffset               int    `json:"address2_utcoffset"`
		Aging30                         int    `json:"aging30"`
		Aging30Base                     int    `json:"aging30_base"`
		Aging60                         int    `json:"aging60"`
		Aging60Base                     int    `json:"aging60_base"`
		Aging90                         int    `json:"aging90"`
		Aging90Base                     int    `json:"aging90_base"`
		Businesstypecode                int    `json:"businesstypecode"`
		Createdby                       string `json:"createdby"`
		Createdon                       int    `json:"createdon"`
		Createdonbehalfby               string `json:"createdonbehalfby"`
		Creditlimit                     int    `json:"creditlimit"`
		CreditlimitBase                 int    `json:"creditlimit_base"`
		Creditonhold                    bool   `json:"creditonhold"`
		Customersizecode                int    `json:"customersizecode"`
		Customertypecode                int    `json:"customertypecode"`
		Defaultpricelevelid             string `json:"defaultpricelevelid"`
		Description                     string `json:"description"`
		Donotbulkemail                  bool   `json:"donotbulkemail"`
		Donotbulkpostalmail             bool   `json:"donotbulkpostalmail"`
		Donotemail                      bool   `json:"donotemail"`
		Donotfax                        bool   `json:"donotfax"`
		Donotphone                      bool   `json:"donotphone"`
		Donotpostalmail                 bool   `json:"donotpostalmail"`
		Donotsendmm                     bool   `json:"donotsendmm"`
		Emailaddress1                   string `json:"emailaddress1"`
		Emailaddress2                   string `json:"emailaddress2"`
		Emailaddress3                   string `json:"emailaddress3"`
		Entityimage                     string `json:"entityimage"`
		EntityimageTimestamp            int    `json:"entityimage_timestamp"`
		EntityimageURL                  string `json:"entityimage_url"`
		Entityimageid                   string `json:"entityimageid"`
		Exchangerate                    int    `json:"exchangerate"`
		Fax                             string `json:"fax"`
		Followemail                     bool   `json:"followemail"`
		Ftpsiteurl                      string `json:"ftpsiteurl"`
		Importsequencenumber            int    `json:"importsequencenumber"`
		Industrycode                    int    `json:"industrycode"`
		Lastonholdtime                  int    `json:"lastonholdtime"`
		Lastusedincampaign              int    `json:"lastusedincampaign"`
		Marketcap                       int    `json:"marketcap"`
		MarketcapBase                   int    `json:"marketcap_base"`
		Marketingonly                   bool   `json:"marketingonly"`
		Masterid                        string `json:"masterid"`
		Merged                          bool   `json:"merged"`
		Modifiedby                      string `json:"modifiedby"`
		Modifiedon                      int    `json:"modifiedon"`
		Modifiedonbehalfby              string `json:"modifiedonbehalfby"`
		MsdynTaxexempt                  bool   `json:"msdyn_taxexempt"`
		Name                            string `json:"name"`
		Numberofemployees               int    `json:"numberofemployees"`
		Onholdtime                      int    `json:"onholdtime"`
		Opendeals                       int    `json:"opendeals"`
		OpendealsDate                   int    `json:"opendeals_date"`
		OpendealsState                  int    `json:"opendeals_state"`
		Openrevenue                     int    `json:"openrevenue"`
		OpenrevenueBase                 int    `json:"openrevenue_base"`
		OpenrevenueDate                 int    `json:"openrevenue_date"`
		OpenrevenueState                int    `json:"openrevenue_state"`
		Originatingleadid               string `json:"originatingleadid"`
		Overriddencreatedon             int    `json:"overriddencreatedon"`
		Ownerid                         string `json:"ownerid"`
		Ownershipcode                   int    `json:"ownershipcode"`
		Owningbusinessunit              string `json:"owningbusinessunit"`
		Owningteam                      string `json:"owningteam"`
		Owninguser                      string `json:"owninguser"`
		Parentaccountid                 string `json:"parentaccountid"`
		Participatesinworkflow          bool   `json:"participatesinworkflow"`
		Paymenttermscode                int    `json:"paymenttermscode"`
		Preferredappointmentdaycode     int    `json:"preferredappointmentdaycode"`
		Preferredappointmenttimecode    int    `json:"preferredappointmenttimecode"`
		Preferredcontactmethodcode      int    `json:"preferredcontactmethodcode"`
		Preferredequipmentid            string `json:"preferredequipmentid"`
		Preferredserviceid              string `json:"preferredserviceid"`
		Preferredsystemuserid           string `json:"preferredsystemuserid"`
		Primarycontactid                string `json:"primarycontactid"`
		Primarysatoriid                 string `json:"primarysatoriid"`
		Primarytwitterid                string `json:"primarytwitterid"`
		Processid                       string `json:"processid"`
		Revenue                         int    `json:"revenue"`
		RevenueBase                     int    `json:"revenue_base"`
		Sharesoutstanding               int    `json:"sharesoutstanding"`
		Shippingmethodcode              int    `json:"shippingmethodcode"`
		Sic                             string `json:"sic"`
		SLACampaignsLA                  string `json:"sla_account_sla"`
		SlainvokedidCampaignsLA         string `json:"slainvokedid_account_sla"`
		Stageid                         string `json:"stageid"`
		StageidProcessstage             string `json:"stageid_processstage"`
		Statecode                       int    `json:"statecode"`
		Statuscode                      int    `json:"statuscode"`
		Stockexchange                   string `json:"stockexchange"`
		Telephone1                      string `json:"telephone1"`
		Telephone2                      string `json:"telephone2"`
		Telephone3                      string `json:"telephone3"`
		Territorycode                   int    `json:"territorycode"`
		Territoryid                     string `json:"territoryid"`
		Tickersymbol                    string `json:"tickersymbol"`
		Timespentbymeonemailandmeetings string `json:"timespentbymeonemailandmeetings"`
		Timezoneruleversionnumber       int    `json:"timezoneruleversionnumber"`
		Transactioncurrencyid           string `json:"transactioncurrencyid"`
		Traversedpath                   string `json:"traversedpath"`
		Utcconversiontimezonecode       int    `json:"utcconversiontimezonecode"`
		Versionnumber                   int    `json:"versionnumber"`
		Websiteurl                      string `json:"websiteurl"`
		Yominame                        string `json:"yominame"`
	} `json:"attributes"`
	FetchMetaInfo bool `json:"fetchMetaInfo"`
}
