package crm_structures

type Create_FormHandlers struct {
	Attributes struct {
		Articlepublicnumber       string `json:"articlepublicnumber"`
		Content                   string `json:"content"`
		Description               string `json:"description"`
		Expirationdate            int    `json:"expirationdate"`
		Expirationstateid         int    `json:"expirationstateid"`
		Expirationstatusid        int    `json:"expirationstatusid"`
		Expiredreviewoptions      int    `json:"expiredreviewoptions"`
		Importsequencenumber      int    `json:"importsequencenumber"`
		Isinternal                bool   `json:"isinternal"`
		Islatestversion           bool   `json:"islatestversion"`
		Isprimary                 bool   `json:"isprimary"`
		Isrootarticle             bool   `json:"isrootarticle"`
		Keywords                  string `json:"keywords"`
		Knowledgearticleid        string `json:"knowledgearticleid"`
		Languagelocaleid          string `json:"languagelocaleid"`
		Majorversionnumber        int    `json:"majorversionnumber"`
		Minorversionnumber        int    `json:"minorversionnumber"`
		Overriddencreatedon       int    `json:"overriddencreatedon"`
		Ownerid                   string `json:"ownerid"`
		Owneridtype               string `json:"owneridtype"`
		Parentarticlecontentid    string `json:"parentarticlecontentid"`
		Previousarticlecontentid  string `json:"previousarticlecontentid"`
		Primaryauthorid           string `json:"primaryauthorid"`
		Processid                 string `json:"processid"`
		Publishon                 int    `json:"publishon"`
		Publishstatusid           int    `json:"publishstatusid"`
		Readyforreview            bool   `json:"readyforreview"`
		Review                    int    `json:"review"`
		Rootarticleid             string `json:"rootarticleid"`
		Scheduledstatusid         int    `json:"scheduledstatusid"`
		Setcategoryassociations   bool   `json:"setcategoryassociations"`
		Setproductassociations    bool   `json:"setproductassociations"`
		Stageid                   string `json:"stageid"`
		Statuscode                int    `json:"statuscode"`
		Subjectid                 string `json:"subjectid"`
		Timezoneruleversionnumber int    `json:"timezoneruleversionnumber"`
		Title                     string `json:"title"`
		Transactioncurrencyid     string `json:"transactioncurrencyid"`
		Traversedpath             string `json:"traversedpath"`
		Updatecontent             bool   `json:"updatecontent"`
		Utcconversiontimezonecode int    `json:"utcconversiontimezonecode"`
	} `json:"attributes"`
}
type Get_FormHandlers struct {
	Attributes struct {
		Articlepublicnumber          string `json:"articlepublicnumber"`
		Content                      string `json:"content"`
		Createdby                    string `json:"createdby"`
		Createdbyname                string `json:"createdbyname"`
		Createdbyyominame            string `json:"createdbyyominame"`
		Createdon                    int    `json:"createdon"`
		Createdonbehalfby            string `json:"createdonbehalfby"`
		Createdonbehalfbyname        string `json:"createdonbehalfbyname"`
		Createdonbehalfbyyominame    string `json:"createdonbehalfbyyominame"`
		Description                  string `json:"description"`
		Exchangerate                 int    `json:"exchangerate"`
		Expirationdate               int    `json:"expirationdate"`
		Expirationstateid            string `json:"expirationstateid"`
		Expirationstatusid           int    `json:"expirationstatusid"`
		Expiredreviewoptions         int    `json:"expiredreviewoptions"`
		Importsequencenumber         int    `json:"importsequencenumber"`
		Isinternal                   bool   `json:"isinternal"`
		Islatestversion              bool   `json:"islatestversion"`
		Isprimary                    bool   `json:"isprimary"`
		Isrootarticle                bool   `json:"isrootarticle"`
		Keywords                     string `json:"keywords"`
		Knowledgearticleid           string `json:"knowledgearticleid"`
		Knowledgearticleviews        int    `json:"knowledgearticleviews"`
		KnowledgearticleviewsDate    int    `json:"knowledgearticleviews_date"`
		KnowledgearticleviewsState   int    `json:"knowledgearticleviews_state"`
		Languagelocaleid             string `json:"languagelocaleid"`
		Languagelocaleidlocaleid     string `json:"languagelocaleidlocaleid"`
		Languagelocaleidname         string `json:"languagelocaleidname"`
		Majorversionnumber           int    `json:"majorversionnumber"`
		Minorversionnumber           int    `json:"minorversionnumber"`
		Modifiedby                   string `json:"modifiedby"`
		Modifiedbyname               string `json:"modifiedbyname"`
		Modifiedbyyominame           string `json:"modifiedbyyominame"`
		Modifiedon                   int    `json:"modifiedon"`
		Modifiedonbehalfby           string `json:"modifiedonbehalfby"`
		Modifiedonbehalfbyname       string `json:"modifiedonbehalfbyname"`
		Modifiedonbehalfbyyominame   string `json:"modifiedonbehalfbyyominame"`
		Overriddencreatedon          int    `json:"overriddencreatedon"`
		Ownerid                      string `json:"ownerid"`
		Owneridname                  string `json:"owneridname"`
		Owneridtype                  string `json:"owneridtype"`
		Owneridyominame              string `json:"owneridyominame"`
		Owningbusinessunit           string `json:"owningbusinessunit"`
		Owningteam                   string `json:"owningteam"`
		Owninguser                   string `json:"owninguser"`
		Parentarticlecontentid       string `json:"parentarticlecontentid"`
		Parentarticlecontentidname   string `json:"parentarticlecontentidname"`
		Previousarticlecontentid     string `json:"previousarticlecontentid"`
		Previousarticlecontentidname string `json:"previousarticlecontentidname"`
		Primaryauthorid              string `json:"primaryauthorid"`
		Primaryauthoridname          string `json:"primaryauthoridname"`
		Processid                    string `json:"processid"`
		Publishon                    int    `json:"publishon"`
		Publishstatusid              int    `json:"publishstatusid"`
		Rating                       int    `json:"rating"`
		RatingCount                  int    `json:"rating_count"`
		RatingDate                   int    `json:"rating_date"`
		RatingState                  int    `json:"rating_state"`
		RatingSum                    int    `json:"rating_sum"`
		Readyforreview               bool   `json:"readyforreview"`
		Review                       int    `json:"review"`
		Rootarticleid                string `json:"rootarticleid"`
		Rootarticleidname            string `json:"rootarticleidname"`
		Scheduledstatusid            int    `json:"scheduledstatusid"`
		Setcategoryassociations      bool   `json:"setcategoryassociations"`
		Setproductassociations       bool   `json:"setproductassociations"`
		Stageid                      string `json:"stageid"`
		Statecode                    int    `json:"statecode"`
		Statuscode                   int    `json:"statuscode"`
		Subjectid                    string `json:"subjectid"`
		Subjectiddsc                 string `json:"subjectiddsc"`
		Subjectidname                string `json:"subjectidname"`
		Timezoneruleversionnumber    int    `json:"timezoneruleversionnumber"`
		Title                        string `json:"title"`
		Transactioncurrencyid        string `json:"transactioncurrencyid"`
		Transactioncurrencyidname    string `json:"transactioncurrencyidname"`
		Traversedpath                string `json:"traversedpath"`
		Updatecontent                bool   `json:"updatecontent"`
		Utcconversiontimezonecode    int    `json:"utcconversiontimezonecode"`
		Versionnumber                int    `json:"versionnumber"`
	} `json:"attributes"`
	ID string `json:"id"`
}
type Update_FormHandlers struct {
	Attributes struct {
		Articlepublicnumber       string `json:"articlepublicnumber"`
		Content                   string `json:"content"`
		Description               string `json:"description"`
		Expirationdate            int    `json:"expirationdate"`
		Expirationstateid         int    `json:"expirationstateid"`
		Expirationstatusid        int    `json:"expirationstatusid"`
		Expiredreviewoptions      int    `json:"expiredreviewoptions"`
		Isinternal                bool   `json:"isinternal"`
		Islatestversion           bool   `json:"islatestversion"`
		Isprimary                 bool   `json:"isprimary"`
		Keywords                  string `json:"keywords"`
		Languagelocaleid          string `json:"languagelocaleid"`
		Majorversionnumber        int    `json:"majorversionnumber"`
		Minorversionnumber        int    `json:"minorversionnumber"`
		Ownerid                   string `json:"ownerid"`
		Owneridtype               string `json:"owneridtype"`
		Parentarticlecontentid    string `json:"parentarticlecontentid"`
		Previousarticlecontentid  string `json:"previousarticlecontentid"`
		Primaryauthorid           string `json:"primaryauthorid"`
		Processid                 string `json:"processid"`
		Publishon                 int    `json:"publishon"`
		Readyforreview            bool   `json:"readyforreview"`
		Review                    int    `json:"review"`
		Rootarticleid             string `json:"rootarticleid"`
		Scheduledstatusid         int    `json:"scheduledstatusid"`
		Setcategoryassociations   bool   `json:"setcategoryassociations"`
		Setproductassociations    bool   `json:"setproductassociations"`
		Stageid                   string `json:"stageid"`
		Statecode                 int    `json:"statecode"`
		Statuscode                int    `json:"statuscode"`
		Subjectid                 string `json:"subjectid"`
		Timezoneruleversionnumber int    `json:"timezoneruleversionnumber"`
		Title                     string `json:"title"`
		Transactioncurrencyid     string `json:"transactioncurrencyid"`
		Traversedpath             string `json:"traversedpath"`
		Updatecontent             bool   `json:"updatecontent"`
		Utcconversiontimezonecode int    `json:"utcconversiontimezonecode"`
	} `json:"attributes"`
}
